#Constants defined for other modules to import

#Screen Constants
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080


#Asteroid Constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_LIFESPAN = 35
ASTEROID_VELOCITY_MULTIPLIER = 1.5  #Currently Only affects asteroids that get hit by a bullet and split

#Player Constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_STARTING_LIVES = 3
PLAYER_INVINCIBILITY_TIMER = 2

#Color Constants
PLAYER_COLOR = [255,255,255]
ASTEROID_COLOR = [255,255,255]
GAMEOVER_COLOR = [255,0,0]
SCREEN_COLOR = [0,0,0]
SHOT_COLOR = [155,0,155]

#Shot Constants
SHOT_RADIUS = 5
SHOT_LIFESPAN = 2